### PR TITLE
Added onScrollUp/onScrollDown and onScrollLeft/onScrollRight

### PR DESCRIPTION
**Pull request by chinalwb**
Thanks a lot for your brilliant work.

For me, I need to detect the direction of scrolling event, up or down for vertical scroller, left or right for horizontal scroller. I made the changes, so could you please help review and merge?

Thanks again.

### CODE REVIEW

**Comment by eberhara** [comment]
Hey @chinalwb , sorry the delay.
Your need is to listen to any scroll in cases where scrolling did not reach the the edge of the container?

**Comment by chinalwb** [comment]
@eberhara N/P, I am waiting for your reply :). Right. I need to change the top/bottom list item style upon scrolling, such that the top and bottom item will be changed while scrolling up/down. I also added the call back for scrolling left/right just want to be keep consistent with yours.
Thanks.

**Comment by eberhara** [comment]
Hey @chinalwb , I just merged this into master and will release a `1.3.0` version.
I am working to update some dependencies to release a `2.0.0`.
In `2.0.0` I am planning to remove the callbacks you added in favor to return the direction being scrolled as part of the `onScroll` callback.

Thank you for your PR!

**Comment by chinalwb** [comment]
Thanks @eberhara , make the direction as a parameter is even better. Thanks again for the great work.

**Comment by eberhara** [comment]
Hey @chinalwb .
I just released version `2.0.1` which is written in react 16 and supports react 15.

One major change is that as of version 2 (released today), the `onScroll` callback receives two parameters:
```jsx
handleScroll = (position, previousPosition) => {
  const diffScroll = position - previousPosition
  const direction = diffScroll > 0
    ? 'down'
    : 'up'

  console.log(`Scroll ${direction} to ${position}`)
}
```

So now you can calculate the horizontal or vertical scroll direction based on position and previous position.

**Comment by chinalwb** [comment]
@eberhara Cool~ Thanks.
So now if I run `npm i --save react-bidirectional-infinite-scroll`, I will get 2.0.1 on my project, right?

**Comment by eberhara** [comment]
Yeah. that's correct @chinalwb !

**Pull request merged**
